# Generated by Django 3.1.7 on 2021-05-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='actual_price',
            field=models.FloatField(default=0, verbose_name='actual price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
        ),
    ]
