# Generated by Django 3.1.7 on 2021-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20210527_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sell_price',
            field=models.FloatField(default=0, verbose_name='sell price'),
        ),
    ]
