# Generated by Django 3.1.7 on 2021-06-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_order_sell_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='order',
            name='average_buy_price',
            field=models.FloatField(default=0, verbose_name='average buy price'),
        ),
    ]
