# Generated by Django 3.1.7 on 2021-08-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_auto_20210624_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_value',
            field=models.FloatField(default=0, verbose_name='wallet value'),
        ),
    ]
