# Generated by Django 3.1.7 on 2021-11-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_order_wallet_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='symbol',
            field=models.CharField(default='BTC', max_length=5, verbose_name='symbol'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='asset',
            field=models.CharField(default='bitcoin', max_length=254, verbose_name='asset'),
        ),
    ]
